### PR TITLE
Updates to Faces and Transcripts

### PR DESCRIPTION
**Pull request by James-Yokley**
Added string for transcript to be used with filestore. Will look into uploading the resulting file to box. Added functionality to faces card to add the time stamps.

### CODE REVIEW

**Review by ajcoolman — APPROVED** [review]
looks good except i want to change the timestamp for faces

**Review by smarque4 — APPROVED** [review]
looks good

**Review by aponc18 — APPROVED** [review]
looks great

**Review by ElYimmy100 — APPROVED** [review]
seems great

**Pull request merged**
